name: Deploy Currency Analysis to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - "projects/currency-analysis/**"
      - "package.json"
      - "package-lock.json"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build Currency Analysis
        run: npm run build:currency-analysis

      - name: Deploy Currency Analysis to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/currency-analysis
          destination_dir: currency-analysis-remote
