name: Deploy Plataform to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - "projects/plataform/**"
      - "package.json"
      - "package-lock.json"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies

        run: npm install

      - name: Build Plataform

        run: npm run build:plataform
        # env:
        #   NODE_ENV: production
        # Se precisar de variáveis de ambiente específicas para a build, adicione aqui

      - name: Deploy Plataform to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/plataform
          # cname: plataform.example.com # Descomente e substitua pelo seu domínio personalizado
